### ISSUE TITLE
Where is the [file with extracted tree]?

### ISSUE THREAD

**Issue by JinyuanShao** [kunxw/LADextract#1]
I am a novice, so please tell me more details.
I don't understand this [fout = r'C:\School\Research\Data\czomi_reynoldCreek\BIN_0410_sage.las'  # file with extracted tree].

Our aim is extracting trees, how can I get this file?
Thanks for your attention.

**Comment by JinyuanShao** [comment]
Would you mind chatting to me by e-mail? I really need your help. This is my e-mail: sx_key@163.com

**Comment by kunxw** [comment]
Notice the variable you ask about is actually used for data output. You can set it to what ever you want.
To learn more about this code, you can refer to section V. of our published paper: http://ieeexplore.ieee.org/document/7762140/?reload=true

**Comment by JinyuanShao** [comment]
Thank you very much!
So I need to run this code at Windows environment? Is Ubuntu OK?

**Comment by kunxw** [comment]
The code is in python, any environment is OK. Just make sure the style of your file paths match that of your environment.
